config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
  end

  root to: "tops#index"

  resources :shops do
    resources :reviews
    resources :clips
    collection do
      get 'search'
    end
    member do
      get 'map'
    end
  end
  resources :users do
    resources :clips
    resources :histories
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many_attached :images
  has_many :reviews, dependent: :destroy
  has_many :shop_caracteristics
  has_many :characteristics, through: :shop_caracteristics, dependent: :destroy
  belongs_to :genre
  belongs_to :area
  has_many :clips
  has_many :users, through: :clips, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :address
    validates :genre_id
    validates :area_id
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.with_attached_images.includes(:area, :genre, :shop_caracteristics, :characteristics, reviews: :user).page(params[:page]).per(5)
    @shops_count = Shop.all.count
  end

  def new
    unless current_user.admin == 1
      flash[:top_message] = '新規店舗登録は権限を持つ人のみ可能です'
      redirect_to root_path
    end
    @shop = Shop.new
  end

  def create
    shop = Shop.new(shop_params)
    if shop.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @shop_rate = if @shop.reviews.present?
                   @shop.reviews.average(:review_point).round(1)
                 else
                   ''
                 end
    @shop_count = @shop.reviews.count
    @clip = Clip.find_by(shop_id: params[:id], user_id: current_user.id) if user_signed_in?
  end

  def edit
    unless current_user.admin == 1
      flash[:top_message] = '店舗情報編集は権限を持つ人のみ可能です'
      redirect_to root_path
    end
      @shop = Shop.find(params[:id])
  end

  def update
    shop = Shop.find(params[:id])
    if shop.update(shop_params)
      redirect_to shop_path(@shop.id)
    else
      render :edit
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy!
    redirect_to root_path
  end

  def search
    @area = params.require(:q)[:area_name_eq]
    @genre = params.require(:q)[:genre_name_eq]
    @characteristic = params.require(:q)[:characteristics_name_eq]
    @area_form = params.require(:q)[:area_name_or_nearest_station_cont]
    @name_form = params.require(:q)[:name_or_genre_name_cont]
  end

  def map
    @shop = Shop.find(params[:id])
    @shop_rate = @shop.reviews.average(:review_point)
    @shop_count = @shop.reviews.count
    @clip = Clip.find_by(shop_id: params[:id], user_id: current_user.id) if user_signed_in?
  end

  private

  def shop_params
    params.require(:shop).permit(
      :name,
      :title,
      :content,
      :open_hour,
      :regular_holiday,
      :telephone,
      :address,
      :nearest_station,
      :capacity,
      :private_room,
      :wifi,
      :power_supply,
      :genre_id,
      :area_id,
      images: [],
      characteristic_ids: []
    )
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  # breadcrumbs用
  def search_word
    if @area.present?
      @area
    elsif @genre.present?
      @genre
    elsif @characteristic.present?
      @characteristic
    elsif @area_form.present?
      @area_form
    elsif @name_form.present?
      @name_form
    end
  end

  def search_result
    if @area.present?
      "#{@area}による検索結果 #{@search_shops_count}件"
    elsif @genre.present?
      "#{@genre}による検索結果 #{@search_shops_count}件"
    elsif @characteristic.present?
      "#{@characteristic}による検索結果 #{@search_shops_count}件"
    elsif @area_form.present?
      "#{@area_form}による検索結果 #{@search_shops_count}件"
    elsif @name_form.present?
      "#{@name_form}による検索結果 #{@search_shops_count}件"
    else
      "店舗一覧 #{Shop.all.count}件"
    end
  end

  def image_display(shop)
    if shop.images.attached?
      image_tag(shop.images[0].variant(resize:'136x136').processed, class:"shop-image")
    else
      image_tag("no_image.jpg", class:"shop-image")
    end
  end

end

app/views/shops/_shop_content.html.erb
<div class="shop">
  <div class="shop-title">
    <p>店舗情報（詳細）</p>
  </div>
  <div class="shop-main">
    <p class="shop-top">店舗基本情報</p>
    <table class="shop-table">
      <tbody>
        <tr><th>店名</th><td><%=@shop.name%></td></tr>
        <tr><th>ジャンル</th><td><%= @shop.genre.name%></td></tr>
        <tr><th>お問い合わせ</th><td><%= @shop.telephone%></td></tr>
        <tr><th>住所</th><td><%= @shop.address%></td></tr>
        <tr><th>最寄り駅</th><td><%= @shop.nearest_station%></td></tr>
        <tr><th>営業時間</th><td><%= @shop.open_hour%></td></tr>
        <tr><th>定休日</th><td><%= @shop.regular_holiday%></td></tr>
      </tbody>
    </table>
  </div>
  <div class="shop-detail">
    <p class="shop-top">席・設備</p>
    <table class="shop-table">
      <tbody>
        <tr><th>席数</th><td><%= @shop.capacity%></td></tr>
        <tr><th>個室</th><td><%= @shop.private_room%></td></tr>
        <tr><th>wifi</th><td><%= @shop.wifi%></td></tr>
        <tr><th>電源</th><td><%= @shop.power_supply%></td></tr>
        <tr><th>こだわり</th><td>
          <% @shop.characteristics.each do |charateristic|%>
            <%= charateristic.name%>
          <% end %></td></tr>
      </tbody>
    </table>
  </div>
</div>

app/views/shops/_shop_info.html.erb
<div class="shop">
  <div class="info">
    <div class="shop-controller">
      <div class="shop-name">
        <%= @shop.name%>
      </div>
      <div class="master">
        <%if user_signed_in? && current_user.admin == 1%>
          <%= link_to "編集", edit_shop_path(@shop.id)%>
          <%= link_to "削除", shop_path(@shop.id), method: :delete %>
        <% end %>
      </div>
    </div>
    <div class="shop-comment">
      <div class="shop-comment-point", id="shop-star-rate-<%=@shop.id%>">
        <script>
          $("#shop-star-rate-<%=@shop.id%>").raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            half: false,
            readOnly: true,
            score: "<%=@shop_rate%>"
          });
        </script>  
        <span><%= @shop_rate%></span>
      </div>
      <div class="shop-comment-count">
        口コミ数<%=@shop_count%>
      </div>
    </div>
    <div class="shop-details">
      <%= "エリア：#{@shop.area.name}"%>
      <%= "ジャンル：#{@shop.genre.name}"%>
      <%= "定休日：#{@shop.regular_holiday}"%>
    </div>
  </div>
  <div class="action">
    <%if user_signed_in?%>
      <% if @clip.present?%>
        <div class="action-btn">
          <%= link_to(shop_clip_path(shop_id: @clip.shop.id, id: @clip.id), method: :delete, class:"action-link") do%>
            <span class="action-name history-delete">保存</span>
          <% end %>
        </div>
      <% else %>
        <div class="action-no-btn">
          <%= link_to(shop_clips_path(@shop.id), method: :post, class:"action-link shop-clip") do%>
            <span class="action-name history-post">保存</span>
          <% end %>
        </div>
      <% end %>
      <div class="action-btn">
        <%=link_to(new_shop_review_path(@shop.id),class:"action-link shop-history") do %>
          <span class="action-name link-clip">行った</span>
          <span class="action-name link-clip-comment">(口コミの投稿)</span>
        <% end %>
      </div>
    <% else %>
      <div class="action-btn">
        <%= link_to(new_user_session_path, class:"action-link shop-clip") do%>
          <span class="action-name history-post">保存</span>
        <% end %>
      </div>
      <div class="action-btn">
        <%=link_to(new_user_session_path,class:"action-link shop-history") do %>
          <span class="action-name link-clip">行った(口コミの投稿)</span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="tab">
  <ul class="shop-menu-bar">
    <li class="shop-menu top-menu">
      <%= link_to(shop_path(@shop.id),class:"shop-menu-link") do%>
        <span class="shop-menu-name">店舗トップ</span>
      <% end %>
    </li>
    <li class="shop-menu review-menu">
      <%= link_to(shop_reviews_path(@shop.id),class:"shop-menu-link") do%>
        <span class="shop-menu-name">口コミ</span>
      <% end %>
    </li>
    <li class="shop-menu map-menu">
      <%= link_to(map_shop_path(@shop.id),class:"shop-menu-link") do%>
        <span class="shop-menu-name">地図</span>
      <% end %>
    </li>
  </ul>
</div>

app/views/shops/edit.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="shop-new-edit">
  <div class="breadcrumbs">
    <% breadcrumb :edit_shop%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="shop-registration">
    <div class="title">
      <p>店舗登録ページ</p>
    </div>
    <div class="shop-forms">
      <%= form_with model:@shop, local: true do |f| %>
        <div class="shop-form">
          <%= f.label "店舗名", class:"shop-label"%>
          <%= f.text_field :name, class:"shop-form-field"%>
        </div>
        <div class="shop-form">
          <%= f.label "紹介タイトル", class:"shop-label" %>
          <%= f.text_field :title, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "説明文", class:"shop-label" %>
          <%= f.text_area :content, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "営業時間", class:"shop-label" %>
          <%= f.text_field :open_hour, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "定休日", class:"shop-label" %>
          <%= f.text_field :regular_holiday, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "住所", class:"shop-label" %>
          <%= f.text_field :address, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "最寄り駅", class:"shop-label" %>
          <%= f.text_field :nearest_station, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "お問い合わせ", class:"shop-label" %>
          <%= f.text_field :telephone, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "総席数", class:"shop-label" %>
          <%= f.text_field :capacity, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "個室", class:"shop-label" %>
          <%= f.text_field :private_room, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "wi-fi", class:"shop-label" %>
          <%= f.text_field :wifi, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "電源", class:"shop-label" %>
          <%= f.text_field :power_supply, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label "エリア", class:"shop-label" %>
          <%= f.collection_select(:area_id, Area.all, :id, :name, {include_blank: "選択してください"}, {class:"select-box", id:"item-category"}) %>
        </div>
        <div class="shop-form">
          <%= f.label "ジャンル", class:"shop-label" %>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "選択してください"}, {class:"select-box", id:"item-category"}) %>
        </div>
        <div class="shop-form shop-check">
          <div class="select-check-label">
            <%= f.label "おすすめポイント", class:"shop-label" %>
          </div>
          <div class="select-check-shop">
            <%= f.collection_check_boxes(:characteristic_ids, Characteristic.all, :id, :name, {}, {class:"select-check-box", id:"item-category"}) %>
          </div>
        </div>
        <div class="shop-form">
          <%= f.label "店舗イメージ1", class:"shop-label" %>
          <div id="shop-image"></div>
          <%= f.file_field :image, name: 'shop[images][]', id:"publish-shop-image" %>
        </div>
        <div class="shop-form">
          <%= f.label "店舗イメージ2", class:"shop-label" %>
          <div id="shop-image"></div>
          <%= f.file_field :image, name: 'shop[images][]', id:"publish-shop-image" %>
        </div>
        <div class="shop-form">
          <%= f.label "店舗イメージ3", class:"shop-label" %>
          <div id="shop-image"></div>
          <%= f.file_field :image, name: 'shop[images][]', id:"publish-shop-image" %>
        </div>
        <div class="shop-send">
          <%= f.submit "登録する" ,class:"shop-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>

app/views/shops/index.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="shop-index">
  <div class="breadcrumbs">
    <% breadcrumb :shops%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="title">
    <span class="title-name">店舗一覧</span>
    <span class="title-count"><%="#{@shops_count}件"%></span>
  </div>
  <div class="master">
    <%if user_signed_in? && current_user.admin == 1%>
      <%= link_to 'お店登録', new_shop_path%>
    <% end %>
  </div>
  <div class="paginate">
    <%= paginate @shops %>
  </div>
  <div class="shop">
    <% @shops.each do |shop| %>
      <div class="shop-list">
        <%= link_to shop_path(shop.id) do %>
          <div class="shop-top">
            <div class="shop-top-name">
                <span class="shop-name"><%= shop.name%></span>
            </div>
            <div class="shop-top-info">
              <div class="shop-top-area">
                <%= "[#{shop.area.name}]"%>
                <%= shop.nearest_station%>
              </div>
              <div class="shop-top-genre">
                <%= "　/　#{shop.genre.name}"%>
              </div>
            </div>
          </div>
          <div class="shop-info">
            <div class="shop-box">
              <%= image_display(shop)%>
            </div>
            <div class="shop-bottom">
              <div class="shop-bottom-title">
                <%= shop.title%>
              </div>
              <div class="shop-bottom-comment">
                <div class="shop-bottom-comment-point", id="shops-star-rate-<%=shop.id%>">
                  <script>
                    $("#shops-star-rate-<%=shop.id%>").raty({
                      size     : 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      readOnly: true,
                      score: "<%=shop.reviews.average(:review_point)%>"
                    });
                  </script>  
                  <% if shop.reviews.present?%>
                    <%= shop.reviews.average(:review_point).round(1)%>
                  <% end %>
                </div>
                <div class="shop-bottom-comment-count">
                  口コミ数<%= shop.reviews.count%>
                </div>
              </div>
              <div class="shop-bottom-characteristic">
                <% shop.characteristics.each do |characteristic|%>
                  <span class="shop-bottom-characteristic-name"><%= characteristic.name%></span>
                <% end %>
              </div>
              <div class="shop-bottom-review">
                <% shop.reviews.first(1).each do |review|%>
                  <span class="shop-bottom-review-title"><%= review.title%></span>
                  <span class="shop-bottom-review-user"><%= "by　#{review.user.name}"%></span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %> 
  </div>
  <div class="paginate">
    <%= paginate @shops %>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>

app/views/shops/map.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="shop-map">
  <div class="breadcrumbs">
    <% breadcrumb :map_shop%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="shop">
    <div class="shop-info">
      <%= render "shop_info"%>
    </div>
    <div class="shop-content">
      <div class="g-map-area">
        <iframe style="border:0; width: 700px; height: 500px" src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['GOOGLE_API_KEY'] %>&q=<%= @shop.address %>" allowfullscreen>
        </iframe>
      </div>
      <div class="shop-map-info">
        <table class="map-table">
          <tbody>
            <tr><th>住所</th><td><%=@shop.address%></td></tr>
            <tr><th>最寄り駅</th><td><%=@shop.nearest_station%></td></tr>
          </tbody>
        </table>
      </div>
      <div class="shop-content-info">
          <%= render "shop_content"%>
      </div>
    </div>
  </div>
</div>

<div class="footer"> 
  <%= render "devise/shared/footer" %>
</div>

app/views/shops/new.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="shop-new-edit">
  <div class="breadcrumbs">
    <% breadcrumb :new_shop %>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="shop-registration">
    <div class="title">
      <p>店舗登録ページ</p>
    </div>
    <div class="shop-forms">
      <%= form_with model:@shop, local: true do |f| %>
        <div class="shop-form">
          <%= f.label :name, "店舗名", class:"shop-label"%>
          <%= f.text_field :name, class:"shop-form-field"%>
        </div>
        <div class="shop-form">
          <%= f.label :title, "紹介タイトル", class:"shop-label" %>
          <%= f.text_field :title, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :content, "説明文", class:"shop-label" %>
          <%= f.text_area :content, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :open_hour, "営業時間", class:"shop-label" %>
          <%= f.text_field :open_hour, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :regular_holiday, "定休日", class:"shop-label" %>
          <%= f.text_field :regular_holiday, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :address, "住所", class:"shop-label" %>
          <%= f.text_field :address, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :nearest_station, "最寄り駅", class:"shop-label" %>
          <%= f.text_field :nearest_station, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :telephone, "お問い合わせ", class:"shop-label" %>
          <%= f.text_field :telephone, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :capacity, "総席数", class:"shop-label" %>
          <%= f.text_field :capacity, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :private_room, "個室", class:"shop-label" %>
          <%= f.text_field :private_room, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :wifi, "wi-fi", class:"shop-label" %>
          <%= f.text_field :wifi, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :power_supply, "電源", class:"shop-label" %>
          <%= f.text_field :power_supply, class:"shop-form-field" %>
        </div>
        <div class="shop-form">
          <%= f.label :area_id, "エリア", class:"shop-label" %>
          <%= f.collection_select(:area_id, Area.all, :id, :name, {include_blank: "選択してください"}, {class:"select-box", id:"item-category"}) %>
        </div>
        <div class="shop-form">
          <%= f.label :genre_id, "ジャンル", class:"shop-label" %>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "選択してください"}, {class:"select-box", id:"item-category"}) %>
        </div>
        <div class="shop-form shop-check">
          <div class="select-check-label">
            <%= f.label :characteristic_ids, "おすすめポイント", class:"shop-label" %>
          </div>
          <div class="select-check-shop">
            <%= f.collection_check_boxes(:characteristic_ids, Characteristic.all, :id, :name, {}, {class:"select-check-box", id:"item-category"}) %>
          </div>
        </div>
        <div class="shop-form">
          <%= f.label :image, "店舗イメージ1", class:"shop-label" %>
          <div id="shop-image"></div>
          <%= f.file_field :image, name: 'shop[images][]', id:"publish-shop-image" %>
        </div>
        <div class="shop-form">
          <%= f.label :image, "店舗イメージ2", class:"shop-label" %>
          <div id="shop-image"></div>
          <%= f.file_field :image, name: 'shop[images][]', id:"publish-shop-image" %>
        </div>
        <div class="shop-form">
          <%= f.label :image, "店舗イメージ3", class:"shop-label" %>
          <div id="shop-image"></div>
          <%= f.file_field :image, name: 'shop[images][]', id:"publish-shop-image" %>
        </div>
        <div class="shop-send">
          <%= f.submit "登録する" ,class:"shop-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>

app/views/shops/search.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="shop-search">
  <div class="breadcrumbs">
    <% breadcrumb :search_shops%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="title">
    <span class="title-name"></span>
    <span class="title-count"><%=search_result%></span>
  </div>
  <div class="master">
    <%if user_signed_in? && current_user.admin == 1%>
      <%= link_to 'お店登録', new_shop_path%>
    <% end %>
  </div>
  <div class="paginate">
    <%= paginate @search_shops %>
  </div>
  <div class="shop">
    <% @search_shops.each do |shop| %>
      <div class="shop-list">
        <%= link_to shop_path(shop.id) do %>
          <div class="shop-top">
            <div class="shop-top-name">
                <span class="shop-name"><%= shop.name%></span>
            </div>
            <div class="shop-top-info">
              <div class="shop-top-area">
                <%= "[#{shop.area.name}]"%>
                <%= shop.nearest_station%>
              </div>
              <div class="shop-top-genre">
                <%= "　/　#{shop.genre.name}"%>
              </div>
            </div>
          </div>
          <div class="shop-info">
            <div class="shop-box">
              <%=image_display(shop)%>
            </div>
            <div class="shop-bottom">
              <div class="shop-bottom-title">
                <%= shop.title%>
              </div>
              <div class="shop-bottom-comment">
                <div class="shop-bottom-comment-point", id="shops-star-rate-<%=shop.id%>">
                  <script>
                    $("#shops-star-rate-<%=shop.id%>").raty({
                      size     : 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHarf: '<%= asset_path('star-half.png')%>',
                      readOnly: true,
                      score: "<%=shop.reviews.average(:review_point)%>"
                    });
                  </script>  
                  <% if shop.reviews.present?%>
                    <%= shop.reviews.average(:review_point).round(1)%>
                  <% end %>
                </div>
                <div class="shop-bottom-comment-count">
                  口コミ数<%= shop.reviews.count%>
                </div>
              </div>
              <div class="shop-bottom-characteristic">
                <% shop.characteristics.each do |characteristic|%>
                  <span class="shop-bottom-characteristic-name"><%= characteristic.name%></span>
                <% end %>
              </div>
              <div class="shop-bottom-review">
                <% shop.reviews.first(1).each do |review|%>
                  <span class="shop-bottom-review-title"><%= review.title%></span> <%#shop.review.first.title にするかもしくはコントローラーにメソッドつくるeachいらない%>
                  <span class="shop-bottom-review-user"><%= "by　#{review.user.name}"%></span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %> 
  </div>
  <div class="paginate">
    <%= paginate @search_shops %>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>

app/views/shops/show.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="shop-show">
  <div class="breadcrumbs">
    <% breadcrumb :shop%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="shop">
    <div class="shop-info">
      <%= render "shop_info"%>
    </div>
    <div class="shop-content">
      <div class="shop-content-image">
        <% if @shop.images.attached?%>
          <div class="shop-images">
            <%= image_tag @shop.images[0].variant(resize:'320x360').processed,class:"shop-image"%>
            <% if @shop.images[1].present?%>
              <%= image_tag @shop.images[1].variant(resize:'320x360').processed,class:"shop-image"%>
            <% end %>
            <% if @shop.images[2].present?%>
              <%= image_tag @shop.images[2].variant(resize:'320x360').processed,class:"shop-image"%>
            <% end %>
          </div>
        <% else %>
          <%= image_tag "no_image.jpg",class:"shop-image"%>
        <% end %>
      </div>
      <div class="shop-content-comment">
        <p class="shop-content-comment-title"><%= @shop.title %></p>
        <p class="shop-content-comment-content"><%= @shop.content%></p>
      </div>
      <div class="shop-content-info">
        <%= render "shop_content"%>
      </div>
    </div>
  </div>
</div>
<div class="footer"> 
  <%= render "devise/shared/footer" %>
</div>