config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
  end

  root to: "tops#index"

  resources :shops do
    resources :reviews
    resources :clips
    collection do
      get 'search'
    end
    member do
      get 'map'
    end
  end
  resources :users do
    resources :clips
    resources :histories
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @shops_count = Shop.all.count
    @top_genres = Genre.limit(5)
    @genres = Genre.all
    @top_areas = Area.limit(5)
    @areas = Area.all
    @top_characteristics = Characteristic.limit(5)
    @characteristics = Characteristic.all
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<div class="header">
  <div class="flash">
    <%= flash[:top_message]%>
  </div>
  <%= render "devise/shared/header" %>
</header>
<div class="top-index">
  <% breadcrumb :root%>
  <%= render "layouts/breadcrumb"%>

  <div class="top">
    <div class="top-title">作業場所探すならWORK-SPACE</div>
  </div>

  <div class="main">
    <div class="area">
      <p class="search-title"><%="大阪　#{@shops_count}件"%></p>
      <div class="area-top">
        <ul class="area-top-list">
          <% @top_areas.each do |top_area| %>
            <li class="area-tops-box">
              <%= link_to top_area.name, search_shops_path(@q, 'q[area_name_eq]': top_area.name),class:"area-top-name"%>
              <span class="area-top-count"><%= "#{top_area.shops.count}件"%></span>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="area-bottom">
        <ul class="area-bottom-list">
          <% @areas.each do |area| %>
            <li class="area-bottom-name">
              <%= link_to area.name, search_shops_path(@q, 'q[area_name_eq]': area.name)%>
            </li>
          <% end %>
          <li class="area-bottom-name">
            <%= link_to "全店舗一覧へ", shops_path %>
          </li>
        </ul>
      </div>
    </div>
    <div class="genre">
      <p class="search-title">ジャンルから探す</p>
      <div class="genre-top">
        <ul class="genre-top-list">
          <% @top_genres.each do |top_genre| %>
            <li class="genre-top-box">
              <%= link_to(search_shops_path(@q, 'q[genre_name_eq]': top_genre.name),class:"genre-top-link") do%>
                <%= image_tag asset_path("#{top_genre.image}"), class:"genre-top-image"%>
                <span class="genre-top-name"><%= top_genre.name%></span>
                <span class="genre-top-count"><%= "#{top_genre.shops.count}件"%></span>
              <%end%>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="genre-bottom">
        <ul class="genre-bottom-list">
          <% @genres.each do |genre| %>
            <li class="genre-bottom-name">
              <%= link_to genre.name, search_shops_path(@q, 'q[genre_name_eq]': genre.name),class:"genre-bottom-link"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="characteristic">
      <p class="search-title">おすすめポイントから探す</p>
      <div class="characteristic-bottom">
        <ul class="characteristic-bottom-list">
          <% @characteristics.each do |characteristic| %>
            <li class="characteristic-bottom-name">
              <%= link_to characteristic.name, search_shops_path(@q, 'q[characteristics_name_eq]': characteristic.name),class:"characteristic-bottom-link"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>