config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
  end

  root to: "tops#index"

  resources :shops do
    resources :reviews
    resources :clips
    collection do
      get 'search'
    end
    member do
      get 'map'
    end
  end
  resources :users do
    resources :clips
    resources :histories
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :clips
  has_many :shops, through: :clips, dependent: :destroy

  validates :name, presence: true
  validates :telephone, length: { maximum: 11 }

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }

  def self.guest
    find_or_create_by!(email: 'test@com') do |user|
      user.password = '111111a'
      user.name = 'ゲストユーザー'
      user.telephone = '00011112222'
      user.image.attach(
        io: File.open("#{Rails.root}/db/images/users/user2.jpg"),
        filename: 'user2.jpg',
        content_type: 'application/jpg'
      )
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy!
    redirect_to root_path
  end

  def new_guest
    user = User.guest
    sign_in user
    flash[:top_message] = 'ゲストユーザーとしてログインしました。'
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.erb
<div class="user">
  <div class="user-box">
    <%if @user.image.attached?%>
      <%= image_tag @user.image.variant(resize:'88x88').processed,class:"user-image"%>
    <% else %>
      <%= image_tag "no_image.jpg",class:"user-image"%>
    <% end %>
  </div>
  <div class="user-top">
    <div class="user-name">
      <%= "#{@user.name}さん のマイページ"%>
    </div>
    <ul class="user-nav-bar">
      <li class="user-nav nav-top">
        <%= link_to(user_path(@user.id),class:"user-nav-link") do%>
          <span class="user-nav-name">トップ</span>
        <% end %>
      </li>
      <li class="user-nav nav-history">
        <%= link_to(user_histories_path(@user.id),class:"user-nav-link") do%>
          <span class="user-nav-name">行ったお店</span>
        <% end %>
      </li>
      <li class="user-nav nav-clip">
        <%= link_to(user_clips_path(@user.id),class:"user-nav-link") do%>
          <span class="user-nav-name">保存したお店</span>
        <% end %>
      </li>
      <%if @user == current_user%>
        <li class="user-nav nav-edit">
          <%= link_to(edit_user_registration_path, class:"user-nav-link") do%>
            <span class="user-nav-name">設定</span>
          <% end %>
        </li>
      <% end %>
      <% if current_user.admin == 1 && @user.admin != 1%>
        <li class="user-nav master-destroy">
          <%= link_to( user_path(@user.id), method: :delete, class:"user-nav-link", data: {confirm: "このアカウントを削除しますか？"}) do%>
            <span class="user-nav-name">削除</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="user-header-line"></div>

app/views/users/show.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="user-show">
  <div class="breadcrumbs">
    <% breadcrumb :user%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="user">
    <div class="user-header">
      <%= render "users/header"%>
    </div>
    <div class="user-info">
      <div class="user-info-comment">
        <span><%= @user.comment %></span>
      </div>
      <ul class="user-info-action">
        <li class="user-action-list">
          <div class="user-action-list-title">行ったお店</div>
          <div class="user-action-list-histories"><%="#{@user.reviews.count}件"%></div>
        </li>
        <li class="user-action-list">
          <div class="user-action-list-title">保存したお店</div>
          <div class="user-action-list-clips"><%="#{@user.clips.count}件"%></div>
        </li>
      </ul>
    </div>
  </div>  
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>