config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
  end

  root to: "tops#index"

  resources :shops do
    resources :reviews
    resources :clips
    collection do
      get 'search'
    end
    member do
      get 'map'
    end
  end
  resources :users do
    resources :clips
    resources :histories
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_review, only: [:edit, :update]
  before_action :set_item, except: [:show, :destroy]

  def index
    @reviews = @shop.reviews.includes(:user)
  end

  def new
    @review = Review.new
  end

  def create
    review = Review.new(review_params)
    if review.save
      redirect_to shop_reviews_path(params[:shop_id])
    else
      render :new
    end
  end

  def edit
    unless current_user == @review.user
      flash[:top_message] = '他人のレビューは編集できません'
      redirect_to root_path 
    end
  end

  def update
    if @review.update(review_params)
      redirect_to shop_reviews_path(params[:shop_id])
    else
      render :index
    end
  end

  def destroy
    if current_user.email == 'test@com'
      flash[:top_message] = 'ゲストユーザーではレビューの削除はできません'
      redirect_to root_path
    else
      review = Review.find(params[:id])
      review.destroy!
      redirect_to shop_reviews_path(params[:shop_id])
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :comment, :review_point, :date).merge(user_id: current_user.id, shop_id: @shop.id)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_item
    @shop = Shop.find(params[:shop_id])
    @shop_rate = if @shop.reviews.present?
                   @shop.reviews.average(:review_point).round(1)
                 else
                   ''
                 end
    @shop_count = @shop.reviews.count
    @clip = Clip.find_by(shop_id: @shop.id, user_id: current_user.id) if user_signed_in?
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="review-new-edit">
  <div class="breadcrumbs">
    <% breadcrumb :edit_shop_review%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="review">
    <div class="review-info">
      <%= render "shops/shop_info"%>
    </div>
    <div class="review-form">
      <div class=review-form-header>
        <span class="form-title">口コミを編集する</span>
      </div>
      <%= form_with model:@review, url: shop_review_path(shop_id: @shop.id, id: @review.id),local: true do |f|%>
        <div class="review-form-body">
          <div class="input-rate", id="star">
            <%= f.label :review_point, "評価"%>
          </div>
          <script>
            $('#star').raty({
              size     : 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              scoreName: 'review[review_point]',
              half: false,
            });
          </script>  
          <div class="input-title">
            <%= f.text_field :title, placeholder: "口コミのタイトルを入力してください", class:"input-review-title"%>
          </div>
          <div class="input-content">
            <%= f.text_area :comment, placeholder: "口コミの内容を入力してください", class:"input-review-content"%>
          </div>
        </div>
        <div class="review-form-footer">
          <div class="visit-date">
            <%= f.label :visit_date, "訪問日"%>
            <%= f.date_field :date,class:"input-visit-date"%>
          </div>
          <div class="send-btn">
            <%= f.submit "登録", class: "review-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>

app/views/reviews/index.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="review-index">
  <div class="breadcrumbs">
    <% breadcrumb :shop_reviews%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="review">
    <div class="review-info">
      <%= render "shops/shop_info"%>
    </div>
    <div class="review-count">
      <p><%="全#{@reviews.count}件"%></p>
    </div>
    <div class="review-detail">
      <%if @reviews.present?%>
        <% @reviews.each do |review|%>
          <div class="review-detail-box">
            <div class="top">
              <div class="user-info">
                <div class="review-image">
                  <%if review.user.image.present?%>
                    <%= image_tag review.user.image,class:"user-image"%>
                  <% else %>
                    <%=image_tag "no_image.jpg",class:"user-image"%>
                  <% end %>
                </div>
                <div class="review-name">
                  <%=link_to(user_path(review.user.id) ,class:"review-user") do%>
                    <span class="user-name"><%=review.user.name%></span>
                  <% end %>
                  <span>の口コミ</span>
                </div>
              </div>
              <div class="master">
                <% if user_signed_in? && (review.user == current_user || current_user.admin == 1)%>
                  <%= link_to "編集", edit_shop_review_path(shop_id: @shop.id, id: review.id)%>
                  <%= link_to "削除", shop_review_path(shop_id: @shop.id, id: review.id), method: :delete, data: {confirm: "削除しますか？"} %>
                <% end %>
              </div>
            </div>
            <div class="review-info">
              <div class="review-rate", id="star-rate-<%=review.id%>">
                <script>
                  $("#star-rate-<%=review.id%>").raty({
                    size     : 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    readOnly: true,
                    score: "<%=review.review_point%>"
                  });
                </script>  
                <span class="review-rate-point"><%= review.review_point%></span>
              </div>
              <div class="review-content">
                <div class="review-visit"><%= "訪問日： #{review.date.year}/#{review.date.month}/#{review.date.day}"%></div>
                <div class="review-title"><%= review.title%></div>
                <div class="review-comment"><%= review.comment%></div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>

app/views/reviews/new.html.erb
<div class="header">
  <%= render "devise/shared/header" %>
</div>
<div class="review-new-edit">
  <div class="breadcrumbs">
    <% breadcrumb :new_shop_review%>
    <%= render "layouts/breadcrumb"%>
  </div>
  <div class="review">
    <div class="review-info">
      <%= render "shops/shop_info"%>
    </div>
    <div class="review-form">
      <div class=review-form-header>
        <span class="form-title">口コミを投稿する</span>
      </div>
      <%= form_with model:@review, url: shop_reviews_path(@shop.id),local: true do |f|%>
        <div class="review-form-body">
          <div class="input-rate", id="star">
            <%= f.label :review_point, "評価"%>
          </div>
          <script>
            $('#star').raty({
              size     : 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              scoreName: 'review[review_point]',
              half: false,
            });
          </script>  
          <div class="input-title">
            <%= f.text_field :title, placeholder: "口コミのタイトルを入力してください", class:"input-review-title"%>
          </div>
          <div class="input-content">
            <%= f.text_area :comment, placeholder: "口コミの内容を入力してください", class:"input-review-content"%>
          </div>
        </div>
        <div class="review-form-footer">
          <div class="visit-date">
            <%= f.label :visit_date, "訪問日"%>
            <%= f.date_field :date,class:"input-visit-date"%>
          </div>
          <div class="send-btn">
            <%= f.submit "登録", class: "review-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="footer">
  <%= render "devise/shared/footer" %>
</div>